/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf9f6',
        'surface-dim': '#dbdad7',
        'surface-bright': '#faf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeeb',
        'surface-container-high': '#e9e8e5',
        'surface-container-highest': '#e3e2e0',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#3f4940',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f2f1ee',
        outline: '#6f7a70',
        'outline-variant': '#bfc9be',
        'surface-tint': '#166c3c',
        primary: '#126a3a',
        'on-primary': '#ffffff',
        'primary-container': '#338350',
        'on-primary-container': '#f6fff4',
        'inverse-primary': '#87d89d',
        secondary: '#5e5e64',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3e1e9',
        'on-secondary-container': '#64646a',
        tertiary: '#934153',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b1596b',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a2f5b7',
        'primary-fixed-dim': '#87d89d',
        'on-primary-fixed': '#00210d',
        'on-primary-fixed-variant': '#00522a',
        'secondary-fixed': '#e3e1e9',
        'secondary-fixed-dim': '#c7c6cd',
        'on-secondary-fixed': '#1a1b20',
        'on-secondary-fixed-variant': '#46464c',
        'tertiary-fixed': '#ffd9de',
        'tertiary-fixed-dim': '#ffb2be',
        'on-tertiary-fixed': '#3f0015',
        'on-tertiary-fixed-variant': '#792c3e',
        background: '#faf9f6',
        'on-background': '#1a1c1a',
        'surface-variant': '#e3e2e0',
        ink: '#14151a',
        'growth-green': '#3e8e5a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '20px',
        'container-max': '1200px',
        gutter: '24px',
        'section-padding': '120px',
      },
      maxWidth: {
        container: '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'title-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md-mobile': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
      },
      boxShadow: {
        card: '0px 4px 20px rgba(20, 21, 26, 0.04)',
        'card-hover': '0px 8px 30px rgba(20, 21, 26, 0.10)',
        cta: '0px 10px 30px rgba(20, 21, 26, 0.15)',
        glow: '0 0 40px rgba(18, 106, 58, 0.12)',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'float-delayed': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        'accordion-down': {
          '0%': { maxHeight: '0', opacity: '0' },
          '100%': { maxHeight: '300px', opacity: '1' },
        },
        'accordion-up': {
          '0%': { maxHeight: '300px', opacity: '1' },
          '100%': { maxHeight: '0', opacity: '0' },
        },
      },
      animation: {
        marquee: 'marquee 30s linear infinite',
        float: 'float 4s ease-in-out infinite',
        'float-delayed': 'float-delayed 4s ease-in-out 2s infinite',
        'fade-in-up': 'fade-in-up 0.45s ease-out forwards',
        'fade-in': 'fade-in 0.4s ease-out forwards',
        'bounce-slow': 'bounce-slow 2s ease-in-out infinite',
        shimmer: 'shimmer 3s linear infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
